name: ${rootProject.name}
version: ${version}
main: fr.fabienhebuterne.whitelistnbt.WhitelistNbt
author: fabien91
api-version: 1.20

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.22
  - com.fasterxml.jackson.core:jackson-core:2.17.1
  - com.fasterxml.jackson.module:jackson-module-kotlin:2.17.1
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.1

commands:
  whitelistnbt:
    usage: /whitelistnbt
    description: Base command
